services:
  - type: web
    name: qr-studio
    runtime: python
    pythonVersion: 3.11
    
    buildCommand: pip install -r requirements.txt && python -c "from app import app, db; app.app_context().push(); db.create_all()"
    startCommand: gunicorn --workers 4 --worker-class sync --bind 0.0.0.0:$PORT --timeout 60 app:app
